# Generated by Django 4.2.6 on 2023-10-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('building', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('technical_equipment', models.TextField(blank=True, null=True)),
                ('organizer_info', models.TextField()),
                ('role', models.IntegerField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronos.place')),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
    ]
