# Generated by Django 4.2.6 on 2023-10-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='role',
            field=models.IntegerField(),
        ),
    ]
